create table if not exists public.transactions (
  ref text primary key,
  amount numeric not null,
  sender text not null,
  recipient text not null,
  bank text not null,
  status text not null default 'settled',
  timestamp timestamptz not null default now(),
  channel text not null default 'wallet_transfer'
);

create table if not exists public.fake_alert_simulations (
  ref text primary key,
  amount numeric not null,
  sender text not null,
  recipient text not null,
  bank text not null,
  status text not null default 'completed',
  timestamp timestamptz not null default now(),
  channel text not null default 'fake_alert_simulation',
  reason text not null
);

insert into public.transactions
  (ref, amount, sender, recipient, bank, status, timestamp, channel)
values
  (
    'OP2026061108731',
    15000,
    'Emeka Johnson',
    'Mama Titi Store',
    'OPay Wallet',
    'settled',
    '2026-06-11T09:11:08Z',
    'wallet_transfer'
  ),
  (
    'OP2026061094421',
    45000,
    'Adebayo Okafor',
    'Kunle Electronics',
    'OPay Wallet',
    'settled',
    '2026-06-11T08:44:21Z',
    'wallet_transfer'
  ),
  (
    'OP2026061072983',
    8500,
    'Fatima Aliyu',
    'Iya Basira Food',
    'OPay Wallet',
    'settled',
    '2026-06-11T07:29:33Z',
    'wallet_transfer'
  ),
  (
    'OP2026061031122',
    120000,
    'Chukwuemeka Nweze',
    'Bello Auto Parts',
    'OPay Wallet',
    'settled',
    '2026-06-11T03:11:55Z',
    'wallet_transfer'
  ),
  (
    'GT2026061055893',
    32500,
    'Ngozi Obi',
    'Mama Titi Store',
    'GTBank',
    'settled',
    '2026-06-11T05:58:43Z',
    'nip_transfer'
  ),
  (
    'ACC2026061188042',
    78000,
    'Sarah Ibeh',
    'Bello Auto Parts',
    'Access Bank',
    'settled',
    '2026-06-11T12:08:42Z',
    'nip_transfer'
  ),
  (
    'ZEN2026061239015',
    22000,
    'Musa Garba',
    'Iya Basira Food',
    'Zenith Bank',
    'settled',
    '2026-06-12T06:39:15Z',
    'nip_transfer'
  ),
  (
    'UBA2026061247710',
    95500,
    'Chioma Eze',
    'Kunle Electronics',
    'UBA',
    'settled',
    '2026-06-12T14:47:10Z',
    'nip_transfer'
  )
on conflict (ref) do update set
  amount = excluded.amount,
  sender = excluded.sender,
  recipient = excluded.recipient,
  bank = excluded.bank,
  status = excluded.status,
  timestamp = excluded.timestamp,
  channel = excluded.channel;

insert into public.fake_alert_simulations
  (ref, amount, sender, recipient, bank, status, timestamp, channel, reason)
values
  (
    'FLASH00001234AB',
    15000,
    'Emeka Johnson',
    'Mama Titi Store',
    'Flash Fund',
    'completed',
    '2026-06-11T09:14:20Z',
    'fake_alert_simulation',
    'Reference was generated by the fake-alert simulator and is not present in public.transactions.'
  ),
  (
    'OP9999999999999',
    65000,
    'Unknown Buyer',
    'Mama Titi Store',
    'Copied Receipt',
    'completed',
    '2026-06-11T10:02:04Z',
    'fake_alert_simulation',
    'Receipt details look complete, but no matching real settlement exists.'
  ),
  (
    'FAKE2026061255100',
    78000,
    'Sarah Ibeh',
    'Bello Auto Parts',
    'Access Bank',
    'completed',
    '2026-06-12T15:51:00Z',
    'fake_alert_simulation',
    'Copied bank-style receipt with a fabricated reference.'
  ),
  (
    'ZEN999888777666',
    22000,
    'Musa Garba',
    'Iya Basira Food',
    'Zenith Bank',
    'successful',
    '2026-06-12T16:05:22Z',
    'fake_alert_simulation',
    'Looks like a bank transfer receipt, but no settlement row exists.'
  )
on conflict (ref) do update set
  amount = excluded.amount,
  sender = excluded.sender,
  recipient = excluded.recipient,
  bank = excluded.bank,
  status = excluded.status,
  timestamp = excluded.timestamp,
  channel = excluded.channel,
  reason = excluded.reason;
