// Local trusted transaction database fallback.
// In production, this is replaced by the Supabase transactions table.

export const MOCK_TRANSACTIONS = {
  "OP2026061108731": {
    ref: "OP2026061108731",
    amount: 15000,
    sender: "Emeka Johnson",
    recipient: "Mama Titi Store",
    bank: "OPay Wallet",
    timestamp: "2026-06-11T09:11:08Z",
    status: "settled",
    channel: "wallet_transfer",
  },
  "OP2026061094421": {
    ref: "OP2026061094421",
    amount: 45000,
    sender: "Adebayo Okafor",
    recipient: "Kunle Electronics",
    bank: "OPay Wallet",
    timestamp: "2026-06-11T08:44:21Z",
    status: "settled",
    channel: "wallet_transfer",
  },
  "OP2026061072983": {
    ref: "OP2026061072983",
    amount: 8500,
    sender: "Fatima Aliyu",
    recipient: "Iya Basira Food",
    bank: "OPay Wallet",
    timestamp: "2026-06-11T07:29:33Z",
    status: "settled",
    channel: "wallet_transfer",
  },
  "OP2026061031122": {
    ref: "OP2026061031122",
    amount: 120000,
    sender: "Chukwuemeka Nweze",
    recipient: "Bello Auto Parts",
    bank: "OPay Wallet",
    timestamp: "2026-06-11T03:11:55Z",
    status: "settled",
    channel: "wallet_transfer",
  },
  "GT2026061055893": {
    ref: "GT2026061055893",
    amount: 32500,
    sender: "Ngozi Obi",
    recipient: "Mama Titi Store",
    bank: "GTBank",
    timestamp: "2026-06-11T05:58:43Z",
    status: "settled",
    channel: "nip_transfer",
  },
  "ACC2026061188042": {
    ref: "ACC2026061188042",
    amount: 78000,
    sender: "Sarah Ibeh",
    recipient: "Bello Auto Parts",
    bank: "Access Bank",
    timestamp: "2026-06-11T12:08:42Z",
    status: "settled",
    channel: "nip_transfer",
  },
  "ZEN2026061239015": {
    ref: "ZEN2026061239015",
    amount: 22000,
    sender: "Musa Garba",
    recipient: "Iya Basira Food",
    bank: "Zenith Bank",
    timestamp: "2026-06-12T06:39:15Z",
    status: "settled",
    channel: "nip_transfer",
  },
  "UBA2026061247710": {
    ref: "UBA2026061247710",
    amount: 95500,
    sender: "Chioma Eze",
    recipient: "Kunle Electronics",
    bank: "UBA",
    timestamp: "2026-06-12T14:47:10Z",
    status: "settled",
    channel: "nip_transfer",
  },
};

export const MOCK_FAKE_ALERTS = {
  "FLASH00001234AB": {
    ref: "FLASH00001234AB",
    amount: 15000,
    sender: "Emeka Johnson",
    recipient: "Mama Titi Store",
    bank: "Flash Fund",
    timestamp: "2026-06-11T09:14:20Z",
    status: "completed",
    channel: "fake_alert_simulation",
    reason: "Reference was generated by the demo fake-alert simulator and is not in the trusted transaction table.",
  },
  "OP9999999999999": {
    ref: "OP9999999999999",
    amount: 65000,
    sender: "Unknown Buyer",
    recipient: "Mama Titi Store",
    bank: "Copied Receipt",
    timestamp: "2026-06-11T10:02:04Z",
    status: "completed",
    channel: "fake_alert_simulation",
    reason: "Receipt details look complete, but no matching real settlement exists.",
  },
  "FAKE2026061255100": {
    ref: "FAKE2026061255100",
    amount: 78000,
    sender: "Sarah Ibeh",
    recipient: "Bello Auto Parts",
    bank: "Access Bank",
    timestamp: "2026-06-12T15:51:00Z",
    status: "completed",
    channel: "fake_alert_simulation",
    reason: "Copied bank-style receipt with a fabricated reference.",
  },
  "ZEN999888777666": {
    ref: "ZEN999888777666",
    amount: 22000,
    sender: "Musa Garba",
    recipient: "Iya Basira Food",
    bank: "Zenith Bank",
    timestamp: "2026-06-12T16:05:22Z",
    status: "successful",
    channel: "fake_alert_simulation",
    reason: "Looks like a bank transfer receipt, but no settlement row exists.",
  },
};

export function verifyTransaction(ref, amount = null, status = null) {
  const trimmed = String(ref || "").trim().toUpperCase();
  const simulatedFake = MOCK_FAKE_ALERTS[trimmed] || MOCK_FAKE_ALERTS[String(ref || "").trim()];

  if (simulatedFake) {
    return {
      found: false,
      fake_found: true,
      fraud_risk: "high",
      simulated_fake: simulatedFake,
      message: "Reference found in the fake-alert simulation database. Do not release goods.",
      checks: [
        { label: "Reference found in fake alerts", ok: true },
        { label: "Reference exists in real transactions", ok: false },
        { label: "Payment can be trusted", ok: false },
      ],
    };
  }

  const found = MOCK_TRANSACTIONS[trimmed] || MOCK_TRANSACTIONS[String(ref || "").trim()];

  if (!found) {
    return {
      found: false,
      fake_found: false,
      fraud_risk: "high",
      simulated_fake: null,
      message: "Reference was not found in the fake database or the real transaction database. Treat it as suspicious.",
      checks: [
        { label: "Reference found in fake alerts", ok: false },
        { label: "Reference exists in real transactions", ok: false },
        { label: "Payment can be trusted", ok: false },
      ],
    };
  }

  const amountMatches = amount === null || Number(amount) === Number(found.amount);
  const statusLooksCompleted = status === null || /completed|successful|approved|settled/i.test(String(status));

  return {
    found: true,
    fake_found: false,
    transaction: found,
    fraud_risk: amountMatches && statusLooksCompleted ? "none" : "medium",
    checks: [
      { label: "Reference exists in real transactions", ok: true },
      { label: "Amount matches real record", ok: amountMatches },
      { label: "Status looks completed", ok: statusLooksCompleted },
    ],
    message: amountMatches
      ? "Transaction matched the reference and amount in the trusted database."
      : "Transaction reference matched, but the receipt amount does not match the stored real record.",
  };
}
